# Problem Statement

The objective of this analysis is to address the following problem:

> "Generate 100,000 samples of size 10 from the standard normal distribution. For each sample, compute the standard deviation with ddof=1 (sample SD) and with ddof=0 (population SD). Plot histograms of both sets of values on the same axes with transparency. Describe the differences you see. Explain how you expect these differences to change if the sample size is increased."

To solve this, we will:

- Generate **100,000 independent samples**, each of size **n = 10**, from the standard normal distribution $N(0, 1)$.
- For every sample, compute two versions of the standard deviation:
  - **Sample Standard Deviation** using `ddof = 1`.
  - **Population Standard Deviation** using `ddof = 0`.
- Compare the distributions of these two methods of calculating the standard deviation by plotting their **histograms on the same axes** with transparency.
- Describe the **visual** and **numerical** differences between the two distributions.
- Explain how and why these differences are expected to change as the **sample size increases**.

The goal is to understand the sampling variability, bias, and distributional behaviour of the standard deviation formulas under repeated sampling.


---

In [55]:
# Libraries Imported

import numpy as np

---

# Standard Normal Distribution

The Standard Normal Distribution is a continuous distribution, perfectly symmetric around the mean. In a Standard Normal Distribution, values are most concentrated near the centre and become increasingly rare as they move further away from the mean. A standard normal distribution is denoted as \( N(0, 1) \), due to the fact it has a mean of \(0\) and a standard deviation of \(1\).

![Standard Normal Distribution](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Standard_deviation_diagram.svg/640px-Standard_deviation_diagram.svg.png)

The bell-shaped curve of the distribution, also referred to as the Gaussian curve, shows how data points are clustered around the mean. This is further demonstrated by the fact that approximately **68.27%** of all values lie within one standard deviation of the mean. This illustrates, within the distribution, the high concentration around the centre or mean. The distribution has no skew and very light tails, demonstrating how the chances of seeing values far from the mean are minimal. The standard normal distribution plays an integral role in statistical theory. This is further demonstrated in the Central Limit Theorem, which shows the reasoning as to why the averages of independent random variables tend to follow a normal distribution.



## Sample Standard Deviation (ddof=1)

In cases where the data represents a subset of the entire population, a sample standard deviation is generally used. In this case, the standard deviation is calculated with `ddof = 1`. The formula in these circumstances divides by $n - 1$ instead of $n$. This adjustment is known as **Bessel’s correction**.

The sample mean $\bar{x} = \frac{\sum x}{n}$ has a propensity to be nearer the sample observations when compared to the true population mean. In turn, if the formula is not modified (i.e., dividing by $n$), then the actual variability is consistently underestimated. By dividing by $n - 1$, this accounts for the issue by slightly increasing the estimate, in turn making the sample variance an unbiased approximation of the population variance.

Due to the impact of **Bessel’s correction**, the sample standard deviation tends to be slightly larger than the standard deviation computed using division by $n$, especially when the sample size is small. The sample standard deviation is calculated using:

$$
s = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n - 1}}
$$



## Population Standard Deviation (ddof=0)

In cases where the data represents an entire population, a population standard deviation is generally used. In this case, the standard deviation is calculated with `ddof = 0`. The formula in these circumstances divides by $N$. This calculation assumes that the true population mean, defined as $\mu = \frac{\sum X}{N}$, should be used in these instances.

There tends to be an underestimation of the true variability when this formula is applied to sample data. This issue arises because the sample mean is an estimate of the population mean; as a result, the deviations from the estimated mean are marginally smaller on average than those from the true population mean. The resulting estimates are biased downwards because no correction is applied.

The population standard deviation tends to be slightly smaller than the sample standard deviation, especially when the sample size is small. The population standard deviation is calculated using:

$$
\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2}
$$

## References For This Section
1. Standard Normal Distribution - https://www.probabilitycourse.com/chapter4/4_2_3_normal.php
2. Standard Normal Distribution - https://www.datacamp.com/blog/standard-normal-distribution
3. Standard Normal Distribution - https://www.geeksforgeeks.org/maths/standard-normal-distribution/
4. Standard Normal Distribution - https://www.analyticsvidhya.com/blog/2020/04/statistics-data-science-normal-distribution/
5. Standard Deviation - https://www.geeksforgeeks.org/maths/standard-deviation-formula/
6. Sample Standard Deviation - https://www.datacamp.com/tutorial/sample-standard-deviation
7. Sample & Population Standard Deviation - https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-sample/a/population-and-sample-standard-deviation-review
8. Sample vs Population Standard Deviation - https://www.statology.org/population-vs-sample-standard-deviation/
9. Bessels Correction - https://www.geeksforgeeks.org/machine-learning/bessels-correction/
10. Bessels Correction - https://towardsdatascience.com/bessels-correction-why-do-we-divide-by-n-1-instead-of-n-in-sample-variance-30b074503bd9/
11. Sample Mean vs Population Mean - https://www.onlinemathlearning.com/population-mean.html
12. Sample Mean vs Population Mean - https://statisticsbyjim.com/basics/sample-mean-vs-population-mean-symbol-formulas/
13. Degrees of Freedom - https://www.statsdirect.com/help/basics/degrees_freedom.html
14. Degrees of Freedom - https://statisticsbyjim.com/hypothesis-testing/degrees-freedom-statistics/
15. Markdown Equations - https://ashki23.github.io/markdown-latex.html
16. Markdown - https://www.markdownguide.org/basic-syntax/
17. Markdown - https://www.datacamp.com/tutorial/markdown-in-jupyter-notebook
18. Markdown - https://github.com/adam-p/markdown-here/wiki/markdown-cheatsheet



---

# Generating The Samples


In [74]:
rng = np.random.default_rng(0) # Ensuring the same random numbers are generated each time

num_samples = 100000 # Setting number of generated samples to be 100000
sample_size = 10 # Setting size of each sample to be 10 observations

samples = rng.standard_normal(size=(num_samples, sample_size)) # Generating samples from standard normal distribution

samples[:3]  # Return first three samples


array([[ 0.12573022, -0.13210486,  0.64042265,  0.10490012, -0.53566937,
         0.36159505,  1.30400005,  0.94708096, -0.70373524, -1.26542147],
       [-0.62327446,  0.04132598, -2.32503077, -0.21879166, -1.24591095,
        -0.73226735, -0.54425898, -0.31630016,  0.41163054,  1.04251337],
       [-0.12853466,  1.36646347, -0.66519467,  0.35151007,  0.90347018,
         0.0940123 , -0.74349925, -0.92172538, -0.45772583,  0.22019512]])

In [ ]:
# Generating sample standard deviation (unbiased)
# Axis 1 indicates we are calculating the standard deviation across the rows (i.e., for each sample)
# ddof=1 sets degrees of freedom to 1, which is used for sample standard deviation
sd_sample = samples.std(axis=1, ddof=1)

sd_sample[:10]  # show first few standard deviations

array([0.78133107, 0.91594062, 0.74051147, 0.72203834, 1.02999039,
       0.81755831, 1.26509651, 1.08975751, 1.01266617, 0.95658268])

In [ ]:
# Generating sample standard deviation (unbiased)
# Axis 1 indicates we are calculating the standard deviation across the rows (i.e., for each sample)
# ddof=1 sets degrees of freedom to 0, which is used for population standard deviation
sd_population = samples.std(axis=1, ddof=0)

sd_population[:10]  # show first few standard deviations

array([0.88559053, 0.68647386, 0.54418506, 0.95115923, 0.41982124,
       0.85401422, 0.74544282, 0.69393798, 0.55688951, 0.76330972])

In [78]:
mean_of_sample_means = samples.mean(axis=1).mean() # Calculating mean of sample means to verify it is close to 0

mean_sd_sample = sd_sample.mean() # Calculating mean of sample standard deviations
mean_sd_population = sd_population.mean() # Calculating mean of population standard deviations

mean_of_sample_means, mean_sd_sample, mean_sd_population # Return the means calculated above

(0.0009985706494386212, 0.9735739275905946, 0.9234252633979069)

As all values were generated from the Standard Normal Distribution \(N(0,1)\), it is anticipated that the mean of the sample means is very close to 0, which it is in this case. Based on the concept of the Law of Large Numbers, by calculating the mean of a large number of Sample Means, it should be relatively close to the actual mean of the population.

It can be seen that the population standard deviation mean, where `ddof = 0`, is noticeably below 1. However, this would be expected as variability tends to be underestimated when the population formula is applied to sample data.

It can be seen that the sample standard deviation mean, where `ddof = 1`, is closer to 1. Again this would be expected, as Bessel’s correction ensures the variance is unbiased, however, the standard deviation, especially in cases of small sample sizes, will remain slightly biased downward.



### References for this section
1. Generating Samples using Numpy - https://www.datacamp.com/doc/numpy/random-normal
2. Generating Samples using Numpy - https://numpy.org/doc/2.1/reference/random/generated/numpy.random.standard_normal.html
3. Generating Samples Using Numpy - https://realpython.com/numpy-random-normal/
4. Generating Samples Using Numpy - https://www.geeksforgeeks.org/python/numpy-random-standard_normal-in-python/
5. Generating Samples Using Numpy - https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_normal.html
6. Generating Sample & Population Standard Deviation - https://www.datacamp.com/tutorial/sample-standard-deviation
7. Axis Parameter - https://www.statology.org/how-to-compute-standard-deviation-and-variance-with-numpy/
8. Axis Parameter - https://www.statology.org/pandas-standard-deviation-for-each-row/
9. Axis Parameter - https://sparkbyexamples.com/pandas/pandas-dataframe-std-method/
10. Central Limit Theorem - https://www.statisticshowto.com/probability-and-statistics/statistics-definitions/sample-mean/
11. Central Limit Theorem - https://www.scribbr.com/statistics/central-limit-theorem/
12. Central Limit Theorem - https://www.geeksforgeeks.org/maths/central-limit-theorem/
13. Sample vs Population Mean - https://www.statology.org/sample-mean-vs-population-mean/
14. Sample vs Population Mean - https://statisticsbyjim.com/basics/sample-mean-vs-population-mean-symbol-formulas/
15. Law of Large Numbers - https://www.datacamp.com/tutorial/law-of-large-numbers

---

# Plotting Histograms

---

# Interpretation of Results

## Visual Interpretation

## Calculated Interpretation - Skewness / Kurtosis

## Expectations if Sample Size Increased